# Default storage class for your cluster
defaultStorageClass: "gp2-csi"

# --- Ghost image configuration ---
image:
  repository: public.ecr.aws/bitnami/ghost
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: []
  debug: false

# --- Ghost configuration ---
ghostUsername: Muhammad
ghostPassword: "Muhammad12345"
ghostEmail: user@example.com
ghostBlogTitle: "User's Blog"
ghostHost: "myargo.duckdns.org"

# --- MySQL dependency configuration ---
mysql:
  image:
    repository: public.ecr.aws/bitnami/mysql
    tag: latest
  architecture: standalone
  auth:
    rootPassword: my-root-password
    username: ghost
    password: ghost123
    database: ghost

# --- Service type (expose via LoadBalancer) ---
service:
  type: LoadBalancer
  port: 80

# --- Persistence configuration ---
persistence:
  enabled: true
  storageClass: "ghost" # You can change this to gp2-csi if "ghost" doesnâ€™t exist
  accessModes:
    - ReadWriteMany
  size: 5Gi
  annotations: {}

# --- Optional security context ---
securityContext:
  enabled: true
  fsGroup: 1001
  runAsUser: 1001
global:
  security:
    allowInsecureImages: true
